// TypeScript bindings for Breaking_Walls_App Emscripten WASM module
// Defines the craft class and factory function generated by Embind

interface WasmModule {
  _main(_0: number, _1: number): number;
}

type EmbindString = ArrayBuffer | Uint8Array | Uint8ClampedArray | Int8Array | string;

export interface ClassHandle {
  isAliasOf(other: ClassHandle): boolean;
  delete(): void;
  deleteLater(): this;
  isDeleted(): boolean;
  [Symbol.dispose](): void;
  clone(): this;
}

/**
 * craft class - Emscripten binding for the C++ craft class
 * Provides maze generation and OBJ export functionality
 */
export interface craft extends ClassHandle {
  get_version(): string;
  begin_export(): void;
  is_export_ready(): boolean;
  get_export(): string;
  get_export_status(): string;
  set_maze_rows(_0: number): void;
  set_maze_columns(_0: number): void;
  set_maze_algo(_0: EmbindString): void;
  set_maze_seed(_0: number): void;
}

/**
 * Module configuration for Emscripten factory
 */
export interface ModuleConfig {
  canvas?: HTMLCanvasElement;
  print?(...args: any[]): void;
  onRuntimeInitialized?(): void;
}

/**
 * Emscripten module with factory functions
 */
interface EmbindModule {
  get(): craft | null;
}

/**
 * Combined module type (low-level WASM + Embind factory)
 */
export type MainModule = WasmModule & EmbindModule;

/**
 * Default export: Emscripten factory function
 * Creates and initializes the WASM module with the provided configuration
 */
export default function MainModuleFactory(
  config?: ModuleConfig
): Promise<MainModule>;
